name: Build and Deploy to IBM Kubernetes Service Cluster

# Execute on every push to master
on:
  workflow_dispatch:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-east
  ICR_REGION: us-south
  ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  REGISTRY_HOSTNAME: us.icr.io
  IKS_CLUSTER: ${{ secrets.IKS_CLUSTER }}
  K8S_CLUSTER_NAMESPACE: ${{ secrets.K8S_CLUSTER_NAMESPACE }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2      
      - name: Add VCAP_LOCAL from secret to development environment
        env:
          VCAP_LOCAL: ${{ secrets.VCAP_LOCAL }}
        run: |
          echo "$VCAP_LOCAL" >> ./prometeo-dashboard/api-auth/vcap-local.json
      
      # A GitHub Action for serializing workflow runs
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: call-for-code/build-push-deploy@main
        with:
          cloud-api-key: $IBM_CLOUD_API_KEY
          cloud-region: $IBM_CLOUD_REGION
          icr-region: $ICR_REGION
          deployment-name: api-main-api-main
          container-name: api-main
          github-sha: $GITHUB_SHA
          icr-namespace: $ICR_NAMESPACE
          image-name: api-main
          k8s-cluster-name: $IKS_CLUSTER
          k8s-cluster-namespace: $K8S_CLUSTER_NAMESPACE
          registry-hostname: us.icr.io
          working-directory: "prometeo-dashboard/api-main"

      - uses: call-for-code/build-push-deploy@938a160985387d0b683b4319d0daf4ec6732b763
        with:
          cloud-api-key: $IBM_CLOUD_API_KEY
          cloud-region: $IBM_CLOUD_REGION
          icr-region: $ICR_REGION
          deployment-name: api-auth-api-auth
          container-name: api-auth
          github-sha: $GITHUB_SHA
          icr-namespace: $ICR_NAMESPACE
          image-name: api-main
          k8s-cluster-name: $IKS_CLUSTER
          k8s-cluster-namespace: $K8S_CLUSTER_NAMESPACE
          registry-hostname: us.icr.io
          working-directory: "prometeo-dashboard/api-auth"

      - uses: call-for-code/build-push-deploy@938a160985387d0b683b4319d0daf4ec6732b763
        with:
          cloud-api-key: $IBM_CLOUD_API_KEY
          cloud-region: $IBM_CLOUD_REGION
          icr-region: $ICR_REGION
          deployment-name: api-dash-api-dash
          container-name: api-dash
          github-sha: $GITHUB_SHA
          icr-namespace: $ICR_NAMESPACE
          image-name: api-main
          k8s-cluster-name: $IKS_CLUSTER
          k8s-cluster-namespace: $K8S_CLUSTER_NAMESPACE
          registry-hostname: us.icr.io
          working-directory: "prometeo-dashboard"

